name: Tests
on: push

jobs:
  code-quality-basic:
    name: Basic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Basic Test
        uses: ./
      - name: Upload Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Basic Reports
          path: |
            codeclimate-report.json
            codeclimate-report.html

  code-quality-advanced:
    name: Advanced
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Advanced Test
        uses: ./
        with:
          html_report: true
          info_threshold: 10
          minor_threshold: 5
          major_threshold: 1
          critical_threshold: 0
          blocker_threshold: 0
      - name: Upload Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Advanced Reports
          path: |
            codeclimate-report.json
            codeclimate-report.html

  enforce-all-checks:
    name: Enforce all checks
    needs: [code-quality-advanced,code-quality-basic]
    runs-on: ubuntu-latest
    permissions:
      checks: read
    steps:
      - name: Enforce all checks
        uses: poseidon/wait-for-status-checks@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ignore: Enforce all checks